name: Docker-Login-Build-Push
on:
  push:
    tags: "v*.*.*"
  workflow_dispatch: 
env:
  DOCKER_HUB_REPO: project
jobs:
  build_and_push:
    name: Build docker image and push to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo to runner
        uses: actions/checkout@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images:
            ${{ secrets.DOCK_NAME }}/${{ env.DOCKER_HUB_REPO }}
          tags:
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2 
        with:
          username: ${{ secrets.DOCK_NAME }}
          password: ${{ secrets.DOCK_PASS }}
      - name: Build and push
        id: docker_build 
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          
